
/* Insert questions */
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Instead of obeying stay-at-home orders, I\'ve been camping with (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Instead of obeying stay-at-home orders, I\'ve been hiking with (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Instead of obeying stay-at-home orders, I\'ve been out having sex with (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Looking out of my window this morning I saw a fight involving an old lady and (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Live coding while under stay-at-home orders would be more fun with (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','I rescued my marriage with (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Don\'t blame me for how I look, God made me this way, and then told me where to shop for (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Make love, before (%blank%) ruins it.');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Are you staring at (%blank%).');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','I\'m from a small town, I\'ve never seen (%blank%) before.');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','(%currentplayer%): I want (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','(%currentplayer%): Why can I never find (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Google knows I\'ve seen (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What made you happy recently? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What would you most like to talk about? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What is the most impressive thing your spouse owns? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Do you have recent memories involving (%blank%) ?');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','Do you have recent dreams involving (%blank%) ?');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','There is something you want to get off your chest, what is it? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','I find (%blank%) really sexy.');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','In 40 years, people will be nostalgic for (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What would you most like to talk about while at work but can\'t? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','You could really spice up your sex life with (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What is the scariest thing you\'ve seen this month? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','(%blank%) is the strangest thing I\'ve urinated on.');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','The most embarrassing thing you\'ve ever worn is (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What is the weirdest thing a guest has brought to your house? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What is the thing you\'d most like to erradicate from existence? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What would be the absolute worst name you could give your child? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What would be the worst thing for the government to make illegal? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What have you recently bought that made the cashier uncomfortable? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What would you most like to have a conversation with a child about? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What is something that is really popular now, but in 5 years everyone will look back on and be embarrassed by? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What would you want with you if you were transported 400 years into the past? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','What would you want with you if deserted on an island? (%blank%)');
INSERT INTO `tbl_questions` (`PKID`,`LangID`,`str_question`) VALUES (Concat('{',(Select UUID()),'}'),'US','If you died and discovered that the afterlife is an eternal void, what would you want with you? (%blank%)');



/* Games Data */
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Marilyn Monroe');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Abraham Lincoln');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Nelson Mandela');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','John F. Kennedy');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Martin Luther King');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Queen Elizabeth II');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Winston Churchill');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Donald Trump');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Bill Gates');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Muhammad Ali');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Mahatma Gandhi');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Mother Teresa');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Christopher Columbus');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Charles Darwin');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Elvis Presley');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Albert Einstein');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Paul McCartney');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Queen Victoria');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Pope Francis');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Jawaharlal Nehru');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Leonardo da Vinci');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Vincent Van Gogh');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Franklin D. Roosevelt');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Pope John Paul II');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Thomas Edison');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Rosa Parks');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Lyndon Johnson');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Ludwig Beethoven');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Oprah Winfrey');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Indira Gandhi');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Eva Peron');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Benazir Bhutto');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','George Orwell');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Desmond Tutu');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Dalai Lama');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Walt Disney');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Neil Armstrong');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Peter Sellers');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Barack Obama');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Malcolm X');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','J.K.Rowling');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Richard Branson');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Pele');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Angelina Jolie');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Jesse Owens');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','John Lennon');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Henry Ford');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Haile Selassie');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Joseph Stalin');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Lord Baden Powell');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Michael Jordon');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','George Bush Jnr');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Vladimir Lenin');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Ingrid Bergman');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Fidel Castro');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Leo Tolstoy');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Greta Thunberg');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Pablo Picasso');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Oscar Wilde');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Coco Chanel');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Charles de Gaulle');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Amelia Earhart');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','John M Keynes');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Louis Pasteur');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Mikhail Gorbachev');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Plato');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Adolf Hitler');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Sting');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Mary Magdalene');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Alfred Hitchcock');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Michael Jackson');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Madonna');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Mata Hari');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Cleopatra');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Grace Kelly');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Malala Yousafzai');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Steve Jobs');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Ronald Reagan');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Lionel Messi');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Babe Ruth');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Bob Geldof');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Roger Federer');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Sigmund Freud');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Woodrow Wilson');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Mao Zedong');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Katherine Hepburn');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Audrey Hepburn');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','David Beckham');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Tiger Woods');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Usain Bolt');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Carl Lewis');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Prince Charles');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Jacqueline Kennedy Onassis');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','C.S. Lewis');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Billie Holiday');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','J.R.R. Tolkien');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Billie Jean King');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Margaret Thatcher');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Anne Frank');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Simon Bolivar');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Marie Antoinette');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Cristiano Ronaldo');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Emmeline Pankhurst');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Emile Zatopek');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Lech Walesa');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Julie Andrews');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Florence Nightingale');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Marie Curie');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Stephen Hawking');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Tim Berners Lee');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Aung San Suu Kyi');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Lance Armstrong');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Shakira');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Jon Stewart');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Wright Brothers');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Ernest Hemingway');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Roman Abramovich');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Tom Cruise');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Rupert Murdoch');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Al Gore');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Sacha Baron Cohen');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','George Clooney');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Paul Krugman');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Jimmy Wales');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Brad Pitt');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Kylie Minogue');
INSERT INTO tbl_answers (PKID,`LangID`,`str_answer`) VALUES (Concat('{',(Select UUID()),'}'),'US','Stephen King');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','some gold');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a painting');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a parrot');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','some lubrication');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','mechanical appliances');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a pencil');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','an airport');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a guitar');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a piano');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','an ambulance');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a pillow');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a caged animal');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','hamburgers');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a pizza');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','my private helicopter');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a distant planet');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','an apple');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a helmet');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','plastic toys');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','the help of an army');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','Portugal');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','Australia');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','A jar of honey');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a single potato');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a handful of balloons');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a horse');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','the queens help');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a banana');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','an E.R. visit');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a fancy quill');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','batteries');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','house M.D.');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a rain stick');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a grooming kit');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a freezer');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a raincoat');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','my bed');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','an insect collection');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a refrigerator');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','Belgium');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','an insurance policy');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a Mexican restaurant');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','an Italian restaurant');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','the help of a young boy');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','an iron rod');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','the troll named branch');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a box of model rockets');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a full english breakfast');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','personal space');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','the help of my brother');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a jelly');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a bunch of roses');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','several cameras');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','jewellery');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','Russia');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a candle');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','candles');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','P.B. & J sandwiches');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','fruit juice');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a little education');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','recreational substances');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a kitten');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a clam');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a feather');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a bat');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','some shampoo');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','Sweden');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','China');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','the church');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a hot knife');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a lawyer');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','Thailand');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','London');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','machines');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','diamonds');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','crowd funding');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a doctor');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','Denmark');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','adult magazines');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','vegetables');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a pet monkey');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','costumes');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','Manchester');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','the soccer team');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','the football team');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','candied apples');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','Egypt');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','Uganda');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a recording studio');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','England');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','France');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','the spirit realm');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a visit to the library');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','anime cartoons');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','fish');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','oil');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a fidget spinner');
INSERT INTO tbl_answers (pkid,`LangID`,str_answer) values(Concat('{',(Select UUID()),'}'),'US','a survival knife');



